### ISSUE TITLE
doc: Provide usage example

### ISSUE THREAD

**Issue by Bo0mer** [abursavich/grpcprom#1]
Hello,

I'm struggling with how to actually hook the package to provide metrics. I've tried the following

```go
	s := grpc.NewServer()
	myService := service.MakeGRPCServer(e)
	pb.RegisterMyService(s, myService)

	// Instrument.
	ms := grpcprom.NewMetrics(grpcprom.MetricsOpts{})
	prometheus.Register(ms)
	ms.InitServer(s)
```

I can actually see the metrics in Prometheus, but they are all zeroes.
I also saw that the `*Metrics` object implements the `stats.Handler` interface, but in order to hook it, one needs to supply it when creating the `grpc.Server`.

Could you please provide a simple usage example.

Thanks,
Ivan

**Comment by Bo0mer** [comment]
Nevermind my question, I figured it out. When one wants to instrument a client:
```go
	ms := grpcprom.NewMetrics(grpcprom.MetricsOpts{})
	conn, err := grpc.Dial(address, grpc.WithInsecure(), grpc.WithStatsHandler(ms.StatsHandler()))
```

And when one wants to instrument a server:
```go
	ms := grpcprom.NewMetrics(grpcprom.MetricsOpts{})
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer(grpc.StatsHandler(ms.StatsHandler()))
	pb.RegisterMyGRPCServer(s, &server{})
	ms.InitServer(s)
```

Thanks for your awesome work!
Cheers,
Ivan

**Comment by abursavich** [comment]
I added an example... and then hacked on [godoc2md](https://github.com/davecheney/godoc2md) for a while to make it support examples.
